#!/usr/bin/env bash

umask 022

function cheftools_profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

  if [[ -n "${thome:-}" ]]; then
    source "$thome/script/profile"
  fi

  # chef_tools
  PATH="$shome/bin:$PATH"
}

cheftools_profile
