#!/usr/bin/env bash

umask 022

function tasks_profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

  # tools
  local thome="$(unset CDPATH; cd -P -- "$(dirname -- "$shome")" && pwd -P)"
  if [[ -d "$thome/tools" ]]; then
    thome="$thome/tools"
  else
    thome="$(unset CDPATH; cd -P -- "$(dirname -- "$shome")/../.." && pwd -P)"
    if [[ -d "$thome/tools/current" ]]; then
      thome="$thome/tools/current"
    else
      echo "WARN: could not find tools deploy" 1>&2
      unset thome
    fi
  fi

  if [[ -n "${thome:-}" ]]; then
    source "$thome/script/profile"
  fi

  # tasks
  PATH="$shome/bin:$shome/exec:$PATH"
}

tasks_profile
